name: Release

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
            git config --global user.name 'Release Workflow'
            git config --global user.email 'francis.owusu@amalitech.com'
      - run: npm install -f
      - run: npm run release --ci
        env: 
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}